### PR TITLE
Fix wrong detections when first resource is relative and when calling a folder without trailing slash

### PR DESCRIPTION
**Pull request by astorije**

### CODE REVIEW

**Comment by dontcallmedom** [comment]
I may be mis-reading this, but this seems to allow any resources linked from the original domain to remain linked from the final document. i.e. if I have an absolute reference to https://w3c.github.io/foo from a document that is being installed from that domain, the tool won't barf (if so, that's a regression).

**Comment by astorije** [comment]
@dontcallmedom (Cc @plehegar), I forgot to add some steps to reproduce the original issue, maybe that will help understand the purpose and need for this PR.

1. In a fresh copy of Echidna, run `npm run testserver
2. In another terminal, in a fresh copy of the third-party-resources-checker, run `./bin/third-party-resources-checker http://localhost:3001/drafts/navigation-timing-2/`

The last command will return the following as an external resource, where it shouldn't: `http://localhost:3001/drafts/navigation-timing-2/spec.css`.

**Comment by astorije** [comment]
@dontcallmedom, I am not sure to follow you, but I am giving a shot. Let me know if I am in the wrong.

My goal here is to fully allow relative links, which seem to be broken at the moment (at least the first one on the page), per my example above.

In the Echidna toolchain, the tool is not run against the source document but after it is installed in temporary location. So no, an absolute reference to `https://w3c.github.io/foo` should not pass even if the source document is here. However, I agree with you that it adds a flaw: if a document makes a (absolute) reference to `https://temp.location/something` while correctly guessing the temp location Echidna is using, then we are publishing a broken document, as this is how we are allowing relative references.
Unless there is a way in Phantom to know if a reference was absolute or relative...

**Comment by dontcallmedom** [comment]
ah indeed, if the document is tested from a non-well-known location, then I think the risk of having such an absolute URL ignored is not problematic.

**Comment by astorije** [comment]
Yes, but that would still be nice to differentiate what URLs are based of the (temp) location because they were relative from those who are absolute...

Thanks for merging!

**Pull request merged**
